### ISSUE TITLE
download() misbehaves with nonexistent `path`

### ISSUE THREAD

**Issue by davharris** [ropensci/ecoretriever#54] opened 2015-09-30 20:39 UTC
If I type, `download("PortalMammals", path = "nonexistent_folder")`, R responds with

```
=> Installing Portal Project Mammals (Ecological Archives 2009)
Copying Portal_rodents_19772002.csv from /Users/davidjharris/.retriever/raw_data/PortalMammals
Copying portal_plots.txt from /Users/davidjharris/.retriever/raw_data/PortalMammals
Copying portal_species.txt from /Users/davidjharris/.retriever/raw_data/PortalMammals
Done!
```

But it looks like these all get written to a *file* called `nonexistent_folder`, and they each overwrite the previous one.

I think it would be better to either have the function create the folder itself or to throw an error saying that the folder doesn't exist.

**Comment by ethanwhite** [comment] 2015-10-01 00:02
Thanks for reporting Dave. What version of the retriever do you have installed. This works the way you thought it should for me with both master and 1.7.0.

**Comment by davharris** [comment] 2015-10-01 00:33
Weird. According to `retriever --version`, I'm on v1.7.0.  I get the same behavior from the command line:

```
$ retriever download PortalMammals -p nonexistent_folder
=> Installing Portal Project Mammals (Ecological Archives 2009)
Copying Portal_rodents_19772002.csv from /Users/davidjharris/.retriever/raw_data/PortalMammals
Copying portal_plots.txt from /Users/davidjharris/.retriever/raw_data/PortalMammals
Copying portal_species.txt from /Users/davidjharris/.retriever/raw_data/PortalMammals
Done!

$ cd nonexistent_folder 
-bash: cd: nonexistent_folder: Not a directory

$ head nonexistent_folder 
New Code;OldCode;ScientificName;Taxa;CommonName;Unknown;Rodent;Shrubland-affiliated
AB;BS, BT;Amphispiza bilineata;Bird;black-throated sparrow;0;0;0
AH;AH;Ammospermophilus harrisi;Rodent-not censused;;0;0;0
AS;AS, GS;Ammodramus savannarum;Bird;;0;0;0
BA;BA;Baiomys taylori;Rodent;Baiomys taylori;0;1;1
CB;CW;Campylorhynchus brunneicapillus;Bird;cactus wren;0;0;0
CM;LB;Calamospiza melanocorys;Bird;lark bunting;0;0;0
CQ;SQ;Callipepla squamata;Bird;scaled quail;0;0;0
CS;CS;Crotalus scutalatus;Reptile;snake;0;0;0
CT;CT;Cnemidophorus tigris;Reptile;lizard;0;0;0
```

I'm on a Mac running 10.10.5 and my default Python installation  (from `python --version`) is 3.4.2 :: Anaconda 2.1.0 (x86_64).  Anything else I can do to help diagnose this?

**Comment by ethanwhite** [comment] 2015-10-01 00:44
Oops. Not weird, me being sloppy. Looks like I hadn't successfully built 1.7.0 and so was still running master. Now that I'm running the right one I can reproduce the error. This was fixed in https://github.com/weecology/retriever/commit/53733226c4239b55df1173dad60fb831526bcd8e and so is fine in master. You can build upgrade to master using:

`pip install --upgrade https://github.com/weecology/retriever/archive/master.zip`

Hopefully we'll have a new release out soon.

**Closed by ethanwhite** 2015-10-01 00:44 UTC

**Comment by davharris** [comment] 2015-10-01 00:46
Okay, cool.  For posterity, it looks like this issue was a duplicate of #205.

**Comment by ethanwhite** [comment] 2015-10-01 00:48
Thanks for reporting!

Here's a direct link to the retriever issue:
https://github.com/weecology/retriever/issues/205
