### ISSUE TITLE
Can't find the retriever right path in MacOs X using RStudio. Works fine using R from the bash

### ISSUE THREAD

**Issue by MarconiS** [ropensci/ecoretriever#76] opened 2017-01-18 18:36 UTC
I am using macOS Sierra 10.12.2, and R version 3.2.4. The error I am experiencing is "Error in system("retriever ls", intern = TRUE) : error in running command". When I try to install.packages('ecoretriever') from the bash, everything works fine.

**Comment by ethanwhite** [comment] 2017-01-18 22:34
Thanks @MarconiS! This is a duplicate of #70 so I'm going to close this and we can continue the conversation over there.

**Closed by ethanwhite** 2017-01-18 22:34 UTC
